### ISSUE TITLE
Documentation/feature request for weighted sampling

### ISSUE THREAD

**Issue by merijn** [jtobin/sampling#5]
As far as I understand from staring at the implementation of the weighted sampling logic, this pretty much relies on the weights summing to 1 (since `psample` and `psampleIO` start with an initial mass of 1).

It would be nice if: 1) this restriction is mentioned in the docs of psample/psampleIO or 2) adjust the implementation to normalise the weights so it works with any set of weights.

**Comment by jtobin** [comment]
I added a little bit of text to the source docs to clarify that!
